#################################################################################
# Clean
#################################################################################
clean_CM:
	@echo "Cleaning up address table autogenerated and downloaded files"
	@rm -f os/*.yaml
	@rm -f kernel/*.yaml
	@echo rm -rf $(shell find ./kernel/ -maxdepth 1 | grep "hw_" | grep -v "hw_user" | xargs)	
	@echo rm -rf $(shell find ./os/ -maxdepth 2 | grep "modules" | xargs)

clean_address_tables:
	@rm -rf os/address_table
#################################################################################
# address tables
#################################################################################

${MAKE_PATH}/os/address_table_%/ :
	mkdir -p ${MAKE_PATH}/os/address_table_$*/

${MAKE_PATH}/os/address_table_%/address_apollo.xml: ${MAKE_PATH}/os/config_%.yaml ${MAKE_PATH}/os/address_table_%/
	./build-scripts/BuildAddressTable.py -l $< -t address_apollo.xml -o os/address_table_$*/modules_$*/ -m modules_$*
	@rm -rf ${MAKE_PATH}/os/address_table
	@ln -s ${MAKE_PATH}/os/address_table_$* ${MAKE_PATH}/os/address_table

${MAKE_PATH}/os/address_table_%/address_%.xml: ${MAKE_PATH}/os/config_%.yaml ${MAKE_PATH}/os/address_table_%/
	./build-scripts/BuildAddressTable.py -l $< -t address_$*.xml -o os/address_table_$*/modules_$*/ -m modules_$*
	@rm -rf ${MAKE_PATH}/os/address_table
	@ln -s ${MAKE_PATH}/os/address_table_$* ${MAKE_PATH}/os/address_table


